set(CPACK_PACKAGE_NAME "SteelTraining")
set(CPACK_PACKAGE_VENDOR "FuckYeahProjects")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/packages")
set(CPACK_GENERATOR "ZIP")
include(CPack)

file(MAKE_DIRECTORY ${CMAKE_SOURCE_DIR}/packages)

# Custom targets for multiple packages
add_custom_target(PACKAGE_MSI COMMAND ${CMAKE_CPACK_COMMAND} -G WIX -C $<CONFIG> ${CMAKE_CURRENT_BINARY_DIR})
add_custom_target(PACKAGE_DEB COMMAND ${CMAKE_CPACK_COMMAND} -G DEB -C $<CONFIG> ${CMAKE_CURRENT_BINARY_DIR})
add_custom_target(PACKAGE_ZIP COMMAND ${CMAKE_CPACK_COMMAND} -G ZIP -C $<CONFIG> ${CMAKE_CURRENT_BINARY_DIR})
set_target_properties(PACKAGE_MSI PROPERTIES FOLDER "Packaging")
set_target_properties(PACKAGE_DEB PROPERTIES FOLDER "Packaging")
set_target_properties(PACKAGE_ZIP PROPERTIES FOLDER "Packaging")